version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Olzhas040404
      POSTGRES_USER: olzzhas
      POSTGRES_DB: java_booking
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: java_booking
    container_name: java_booking
    ports:
      - "8081:8080"
    depends_on:
      - db